pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('lab5.2') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('lab5.2') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('lab5.2') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

    }

    post {
        success {
            echo 'SnapCart provisioned by Terraform via Jenkins.'
        }
        failure {
            echo 'Pipeline failed. Check the console output.'
        }
    }
}
